//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mshop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccSale
    {
        public int Bid { get; set; }
        public string Saleid { get; set; }
        public string Employeeid { get; set; }
        public string Customerid { get; set; }
        public string Aid { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> TotalAmount { get; set; }
    }
}
