//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mshop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Employeeid { get; set; }
        public string EmployeeName { get; set; }
        public string Position { get; set; }
        public Nullable<double> Salary { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string PhNo { get; set; }
        public byte[] ProfileImage { get; set; }
    }
}
