//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mshop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Extra
    {
        public string Aid { get; set; }
        public string BrandName { get; set; }
        public string Type { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Stock { get; set; }
        public Nullable<double> Warranty { get; set; }
    }
}
