//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mshop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileType
    {
        public string Mobileid { get; set; }
        public string MobileName { get; set; }
    }
}
