//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mshop.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mobile_ShopEntities : DbContext
    {
        public Mobile_ShopEntities()
            : base("name=Mobile_ShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccSale> AccSales { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Extra> Extras { get; set; }
        public virtual DbSet<MobileType> MobileTypes { get; set; }
        public virtual DbSet<Repair> Repairs { get; set; }
        public virtual DbSet<MobileModel> MobileModels { get; set; }
        public virtual DbSet<SaleInfo> SaleInfoes { get; set; }
        public virtual DbSet<PhoneOrder> PhoneOrders { get; set; }
    }
}
