//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mshop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileModel
    {
        public int Typeid { get; set; }
        public string Mobileid { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> Warranty { get; set; }
    }
}
