//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mshop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneOrder
    {
        public string Orderid { get; set; }
        public string Customername { get; set; }
        public string Oaddress { get; set; }
        public string Oph { get; set; }
        public string PhoneType { get; set; }
        public string PhoneModel { get; set; }
        public string PhoneColor { get; set; }
        public Nullable<System.DateTime> NowDate { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Delivery { get; set; }
        public string Employeeid { get; set; }
    }
}
